# Use postgres/example user/password credentials
# http://localhost:9090/swagger-ui.html
# http://localhost:8080  -> adminer panel giris ->
#                                       postgresql, dbPostgres, postgres, alperen123, portal
version: '3.6'

services:

  portal:
    image: project:0.0.1
    ports:
      - 9090:7070
    depends_on:
      - dbPostgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbPostgres:5432/portal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: alperen123
      spring.jpa.hibernate.ddl-auto: update

  dbPostgres:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alperen123
      POSTGRES_DB: portal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080